export const EnemyColors = {
    "ey": "#ffff57",
    "sk": "#100f0f",
    "lc": "#a80000",
    "mc": "#641f14",
    "dc": "#431313",
};

export const PlayerColors = {
    "ey": "#ffff57",
    "sk": "#100f0f",
    "lc": "#10495e",
    "mc": "#3e3846",
    "dc": "#38252e",
};

export const CharacterSideIddle = [
    [
        [null, null, null, null, null, null, "sk", null, null, null, null, "sk", null, null, null, null],
        [null, null, null, null, null, null, "sk", "sk", null, null, "sk", "sk", null, null, null, null],
        [null, null, null, null, null, null, "lc", "lc", "lc", "lc", "lc", "lc", null, null, null, null],
        [null, null, null, null, "mc", "mc", "sk", "lc", "lc", "lc", "lc", "lc", "mc", null, null, null],
        [null, null, null, "mc", "mc", null, "sk", "sk", "ey", "sk", "sk", "ey", "mc", "mc", null, null],
        [null, null, "mc", "mc", null, null, "sk", "sk", "sk", "sk", "sk", "sk", null, "mc", null, null],
        [null, null, null, null, "dc", "dc", "dc", "sk", "sk", "sk", "sk", "sk", null, null, null, null],
        [null, null, null, "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", null, null, null],
        [null, null, null, "dc", "dc", null, "dc", "dc", "dc", "dc", "dc", "dc", "dc", null, null, null],
        [null, null, null, "mc", null, null, "lc", "lc", "lc", "lc", "lc", null, "mc", null, null, null],
        [null, null, null, "sk", null, "dc", "dc", "dc", "mc", "dc", "dc", "dc", "sk", null, null, null],
        [null, null, null, null, "dc", "dc", "dc", "dc", "mc", "dc", "dc", "dc", "dc", null, null, null],
        [null, null, null, null, "dc", "dc", "dc", null, null, null, "dc", "dc", "dc", null, null, null],
        [null, null, null, null, "dc", null, null, null, null, null, null, "dc", null, null, null, null],
        [null, null, null, null, "mc", null, null, null, null, null, null, "mc", null, null, null, null],
        [null, null, null, null, "sk", "sk", null, null, null, null, null, "sk", "sk", null, null, null],
    ],
    [
        [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, "sk", null, null, null, null, "sk", null, null, null, null],
        [null, null, null, null, null, null, "sk", "sk", null, null, "sk", "sk", null, null, null, null],
        [null, null, "mc", "mc", "mc", null, "lc", "lc", "lc", "lc", "lc", "lc", "mc", "mc", null, null],
        [null, null, null, null, "mc", "mc", "sk", "lc", "lc", "lc", "lc", "lc", "mc", null, null, null],
        [null, null, null, null, null, null, "sk", "sk", "ey", "sk", "sk", "ey", null, null, null, null],
        [null, null, null, null, null, null, "sk", "sk", "sk", "sk", "sk", "sk", null, null, null, null],
        [null, null, null, null, "dc", "dc", "dc", "sk", "sk", "sk", "sk", "sk", null, null, null, null],
        [null, null, null, "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", null, null, null],
        [null, null, null, "dc", "dc", null, "dc", "dc", "dc", "dc", "dc", "dc", "dc", null, null, null],
        [null, null, null, "mc", null, null, "lc", "lc", "lc", "lc", "lc", null, "mc", null, null, null],
        [null, null, null, "sk", null, "dc", "dc", "dc", "mc", "dc", "dc", "dc", "sk", null, null, null],
        [null, null, null, null, "dc", "dc", "dc", "dc", "mc", "dc", "dc", "dc", "dc", null, null, null],
        [null, null, null, null, "dc", "dc", "dc", null, null, null, "dc", "dc", "dc", null, null, null],
        [null, null, null, null, "mc", null, null, null, null, null, null, "mc", null, null, null, null],
        [null, null, null, null, "sk", "sk", null, null, null, null, null, "sk", "sk", null, null, null],
    ],
];

export const CharacterJump = [
    [
        [null, null, null, null, null, null, null, null, null, null, "sk", null, null, null, null, "sk"],
        [null, null, null, null, null, null, null, null, null, null, "sk", "sk", null, null, "sk", "sk"],
        [null, null, null, null, null, null, null, null, null, null, "lc", "lc", "lc", "lc", "lc", "lc"],
        [null, null, null, null, null, null, null, null, "mc", "mc", "sk", "lc", "lc", "lc", "lc", "lc"],
        [null, null, null, null, null, null, null, "mc", "mc", null, "sk", "sk", "ey", "sk", "sk", "ey"],
        [null, null, null, null, null, null, "mc", "mc", null, null, "sk", "sk", "sk", "sk", "sk", "sk"],
        [null, null, null, null, null, null, null, "dc", "dc", "dc", "dc", "sk", "sk", "sk", "sk", "sk"],
        [null, null, null, null, null, null, "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", null],
        [null, null, null, null, null, "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", null],
        [null, null, null, null, "mc", "mc", null, null, "lc", "lc", "lc", "lc", "lc", null, "mc", null],
        [null, null, null, "sk", null, null, null, "dc", "dc", "dc", "mc", "dc", "dc", null, "sk", null],
        [null, null, null, null, null, null, "dc", "dc", "dc", "dc", "mc", "dc", "dc", "dc", null, null],
        [null, null, null, null, null, "dc", "dc", "dc", "dc", null, null, "dc", "dc", "dc", null, null],
        [null, null, null, null, "dc", "dc", "dc", null, null, null, "mc", "dc", "dc", null, null, null],
        [null, null, null, null, "mc", null, null, null, null, null, "sk", null, null, null, null, null],
        [null, null, null, "sk", null, null, null, null, null, null, null, null, null, null, null, null],
    ],
    [
        [null, null, null, null, null, null, null, null, null, "sk", null, null, null, null, "sk", null],
        [null, null, null, null, null, null, null, null, null, "sk", "sk", null, null, "sk", "sk", null],
        [null, null, null, null, null, null, null, null, null, null, "lc", "lc", "lc", "lc", "lc", "lc"],
        [null, null, null, null, null, null, null, "mc", "mc", "mc", "sk", "lc", "lc", "lc", "lc", "lc"],
        [null, null, null, null, null, "mc", "mc", "mc", null, null, "sk", "sk", "ey", "sk", "sk", "ey"],
        [null, null, null, null, null, null, null, null, null, null, "sk", "sk", "sk", "sk", "sk", "sk"],
        [null, null, null, null, null, null, null, "dc", "dc", "dc", "dc", "sk", "sk", "sk", "sk", "sk"],
        [null, null, null, null, null, null, "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", null],
        [null, null, null, null, null, "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", null],
        [null, null, null, null, "mc", "mc", null, null, "lc", "lc", "lc", "lc", "lc", null, "mc", null],
        [null, null, null, "sk", null, null, null, "dc", "dc", "dc", "mc", "dc", "dc", null, "sk", null],
        [null, null, null, null, null, null, "dc", "dc", "dc", "dc", "mc", "dc", "dc", "dc", null, null],
        [null, null, null, null, null, "dc", "dc", "dc", "dc", null, null, "dc", "dc", "dc", null, null],
        [null, null, null, null, "dc", "dc", "dc", null, null, null, "mc", "dc", "dc", null, null, null],
        [null, null, null, null, "mc", null, null, null, null, null, "sk", null, null, null, null, null],
        [null, null, null, "sk", null, null, null, null, null, null, null, null, null, null, null, null],
    ],
];

export const CharacterFall = [
    [
        [null, null, null, null, null, null, "mc", null, null, null, "sk", null, null, null, null, "sk"],
        [null, null, null, null, null, null, "mc", "mc", null, null, "sk", "sk", null, null, "sk", "sk"],
        [null, null, null, null, null, null, null, "mc", "mc", null, "lc", "lc", "lc", "lc", "lc", "lc"],
        [null, null, null, null, null, null, "dc", "dc", "mc", "mc", "sk", "lc", "lc", "lc", "lc", "lc"],
        [null, null, null, null, null, "mc", "dc", "dc", "dc", "dc", "sk", "sk", "ey", "sk", "sk", "ey"],
        [null, null, null, null, "sk", null, null, "dc", "dc", "dc", "sk", "sk", "sk", "sk", "sk", "sk"],
        [null, null, null, null, null, null, null, "dc", "dc", "dc", "dc", "sk", "sk", "sk", "sk", "sk"],
        [null, null, null, null, null, null, null, null, "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc"],
        [null, null, null, null, null, null, null, null, "dc", "dc", "dc", "dc", "dc", "dc", null, "mc"],
        [null, null, null, null, null, null, null, null, "lc", "lc", "lc", "lc", "lc", null, null, "sk"],
        [null, null, null, "sk", null, null, "dc", "dc", "dc", "dc", "mc", "dc", "dc", null, null, null],
        [null, null, null, null, "mc", "dc", "dc", "dc", "dc", "dc", "mc", "dc", "dc", "dc", null, null],
        [null, null, null, null, null, "dc", "dc", "dc", "dc", null, null, "dc", "dc", "dc", null, null],
        [null, null, null, null, null, null, null, null, null, "sk", "mc", "dc", "dc", null, null, null],
    ],
    [
        [null, null, null, null, "mc", null, null, null, null, "sk", null, null, null, null, "sk", null],
        [null, null, null, null, null, "mc", "mc", "mc", null, "sk", "sk", null, null, "sk", "sk", null],
        [null, null, null, null, null, null, null, "mc", "mc", null, "lc", "lc", "lc", "lc", "lc", "lc"],
        [null, null, null, null, null, null, "dc", "dc", "mc", "mc", "sk", "lc", "lc", "lc", "lc", "lc"],
        [null, null, null, null, null, "mc", "dc", "dc", "dc", "dc", "sk", "sk", "ey", "sk", "sk", "ey"],
        [null, null, null, null, "sk", null, null, "dc", "dc", "dc", "sk", "sk", "sk", "sk", "sk", "sk"],
        [null, null, null, null, null, null, null, "dc", "dc", "dc", "dc", "sk", "sk", "sk", "sk", "sk"],
        [null, null, null, null, null, null, null, null, "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc"],
        [null, null, null, null, null, null, null, null, "dc", "dc", "dc", "dc", "dc", "dc", null, "mc"],
        [null, null, null, null, null, null, null, null, "lc", "lc", "lc", "lc", "lc", null, null, "sk"],
        [null, null, null, "sk", null, null, "dc", "dc", "dc", "dc", "mc", "dc", "dc", null, null, null],
        [null, null, null, null, "mc", "dc", "dc", "dc", "dc", "dc", "mc", "dc", "dc", "dc", null, null],
        [null, null, null, null, null, "dc", "dc", "dc", "dc", null, null, "dc", "dc", "dc", null, null],
        [null, null, null, null, null, null, null, null, null, "sk", "mc", "dc", "dc", null, null, null],
    ],
];

export const CharacterRun = [
    [
        [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, "sk", null, null, null, null, "sk", null, null],
        [null, null, null, null, null, null, null, null, "sk", "sk", null, null, "sk", "sk", null, null],
        [null, null, null, "mc", "mc", "mc", null, null, "lc", "lc", "lc", "lc", "lc", "lc", null, null],
        [null, null, null, null, null, "mc", "mc", "mc", "sk", "lc", "lc", "lc", "lc", "lc", null, null],
        [null, null, null, null, null, null, null, null, "sk", "sk", "ey", "sk", "sk", "ey", null, null],
        [null, null, null, null, null, null, null, null, "sk", "sk", "sk", "sk", "sk", "sk", null, null],
        [null, "sk", "mc", "dc", "dc", "dc", "dc", "dc", "dc", "sk", "sk", "sk", "sk", "sk", null, null],
        [null, null, null, "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", null, null, null],
        [null, null, null, null, null, "dc", "dc", "dc", "dc", "dc", "dc", "dc", null, null, null, null],
        [null, null, null, null, null, null, "lc", "lc", "lc", "lc", "lc", null, null, null, null, null],
        [null, null, null, null, null, "dc", "dc", "mc", "dc", "dc", "dc", "sk", "sk", null, null, null],
        [null, null, null, null, "dc", "dc", "dc", "dc", "dc", "sk", "sk", "sk", "sk", null, null, null],
        [null, null, null, "dc", "dc", "dc", "dc", null, null, null, "sk", "sk", null, null, null, null],
        [null, null, "mc", "mc", null, null, null, null, null, null, null, null, null, null, null, null],
        [null, "sk", null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    ],
    [
        [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, "sk", null, null, null, null, "sk", null, null, null],
        [null, null, null, null, null, null, null, "sk", "sk", null, null, "sk", "sk", null, null, null],
        [null, null, null, null, null, null, null, null, "lc", "lc", "lc", "lc", "lc", "lc", null, null],
        [null, null, null, "mc", "mc", "mc", "mc", "mc", "sk", "lc", "lc", "lc", "lc", "lc", null, null],
        [null, null, null, null, null, null, null, null, "sk", "sk", "ey", "sk", "sk", "ey", null, null],
        [null, null, null, null, null, null, null, null, "sk", "sk", "sk", "sk", "sk", "sk", null, null],
        [null, "sk", "mc", "dc", "dc", "dc", "dc", "dc", "dc", "sk", "sk", "sk", "sk", "sk", null, null],
        [null, null, null, "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", "dc", null, null, null],
        [null, null, null, null, null, null, "lc", "lc", "lc", "lc", "lc", null, null, null, null, null],
        [null, null, null, null, null, null, "sk", "dc", "dc", "dc", "dc", "dc", null, null, null, null],
        [null, null, null, null, null, "sk", "sk", "sk", "dc", "dc", "dc", "dc", null, null, null, null],
        [null, null, null, null, "sk", "sk", "sk", "mc", "dc", "dc", "dc", "dc", null, null, null, null],
        [null, null, null, "dc", "dc", null, null, null, "dc", "dc", "dc", null, null, null, null, null],
        [null, null, "sk", null, null, null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    ],
];